### ISSUE TITLE
ItemsAdder official addon

### ISSUE THREAD

**Issue by LoneDev6** [Slimefun/Slimefun-Wiki#58]
## Description
I created an addon for ItemsAdder which adds textures to Slimefun 

## Addon Resources (if applicable)
https://www.spigotmc.org/resources/addon-slimefun-compatibility-for-itemsadder.83877/

## Slimefun Version
Slimefun version RC - 16 (git 7ce2793d)

**Comment by TheBusyBiscuit** [comment]
First and foremost, please **do not** use our logo for your resources... You don't own the rights to that image and our Artist does not approve of such usage.

Furthermore... Ihave to admit that I haven't looked into that "addon" too deeply, but it seems like you are using some resourcepack made by "RaulH22" there. We don't support that resourcepack and never did as it too is subject to multiple copyright violations of other mod authors.

We always like to see integrations and compatibility layers with other plugins!
But we won't approve of theft and copyright violations.

If you wanna add some sort of compatibility (again I haven't looked into what exactly this resource does) then I would suggest you to use our **official** `item-models`  mappings found under "Assets" right here: https://github.com/Slimefun/Resourcepack/releases<br>
But do keep in mind that Slimefun allows server owners to set their own custom model-data mappings, so I would suggest to either stick to the official resourcepack mappings of Slimefun instead of supporting a third-party copyright-violation or (if possible) to look into some way of automatically reading the server-configured values. (Again, I don't know how ItemsAdder works, so not sure on that).

**Comment by LoneDev6** [comment]
Thanks for the info! 
Sadly I didn't notice that you got an official pack that's why I decided to port the other one. Seems I'd have to redo the manual conversion again 🤦‍♂️

**Comment by LoneDev6** [comment]
Do you think I have to remove the resource in the meantime? I didn't think that it violated copyrights of anyone.

**Comment by TheBusyBiscuit** [comment]
No problem! To be fair our official resourcepack is still WIP but the mappings are pretty much set as our standard ones and there for people to use.

It's completely your call on how to handle this resource then, you can of course remove it and put it up at a later point in time, but that's entirely your decision.

Anyway, thanks for the effort, the understanding and for removing our logo from that page.
Feel free to get back to us once you got anything new to share! :)

**Comment by LoneDev6** [comment]
No problem! I understand your point completely, I will convert your official pack to ItemsAdder and replace the bad one I shared (I temporarily removed the download link)

Have a nice day


Anyway if you're curious the test server is this one: test.plugin.ga

**Comment by LoneDev6** [comment]
Anyway I contacted the author to be sure if it does violate copyright or not, because this is what I read in a recent update:
- All textures has been remaked 
- Apology update, all mod textures have been removed. If you find any, let me know. Sorry for the misuse of any texture, the purpose of Slimefun Texture was configs, not art itself.

So MAYBE he managed to draw the textures on his own to avoid copyright issues.
Let's wait his answer.

(I know you may not care about that since even if he answers that textures are not copyrighted anymore you'd surely don't want approve a third party resourcepack, but I want others to know if this pack is legit or not)

**Comment by TheBusyBiscuit** [comment]
Oh, didn't know that. I will look into it myself the coming days and maybe contact the author too (he is on our discord server anyway). But yeah that would be awesome, if he removed 

As long as their content doesn't violate laws or other people's rights, I would be completely fine to support third-party creators.
We have lots of third-party addons anyway.

And the original plan for the (near or far) future was to have a proper Resourcepack installer inside Slimefun itself or as an addon but that would require others to follow our standard item-model mappings and to support server owners custom ones too, so third-party resourcepacks are definitely nothing unwanted in itself here.

**Comment by LoneDev6** [comment]
Very nice!
Well I hope he answers so we can re-evaluate this resourcepack reliability

**Comment by Andre601** [comment]
Just to answer this hrre - since LoneDev didn't really answer it outside of providing a link to his test server - ItemsAdder is a plugin that allows people to add their own custom items including custom durability, effects and behaviour.

It generates a zip file based on what item packs are active and *would* make it available through a custom port.
Although a set url can be used.

That's my tl:dr of it.

**Comment by SnowBees** [comment]
I am very happy to be able to unify the texture of Slimefun with itemsadder!

There are some publicly available texture packs that even support Slimefun add-ons, so use this as well. If you can get permission
I think that by combining it, it will probably be possible to correspond to all items and items of additional add-ons.
However, since this uses the CIT function of Optifine and is not a custom model, I think that json editing is necessary.

I'm just an introducer.
I have not heard about the license.
sorry!

Slimefun Resources v3.0 (1.12-1.15)
https://www.planetminecraft.com/texture-pack/slimefun-resources-v1-0/
by: HauntedCorpse

**Comment by RaulH22** [comment]
Hi, I wanted to say that it was never my intention to steal anything ... I was just trying to help the Slimufun community. And I have already removed all textures that were not my own.

**Comment by LoneDev6** [comment]
Very nice :D
Thanks for your effort!
